name: Publicar

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.repository.default_branch }}

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Instalar Dependencias
        run: pnpm install

      - name: Lanzar Checks
        run: pnpm run ci

      - name: Actualizar package.json con tag
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "Actualizando package.json a versión $TAG"
          pnpm version "$TAG" --no-git-tag-version

      - name: Confirmar y subir actualización de versión
        run: |
          TAG="${{ github.event.release.tag_name }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json pnpm-lock.yaml
          git commit -m "Actualizar package.json a version $TAG"
          git push origin ${{ github.event.repository.default_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: simenandre/publish-with-pnpm@v2
        with:
          npm-auth-token: ${{ secrets.NPM_TOKEN }}
